// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrXbZ8h2JtT1jlctMmhYotsBsyg4-IJE',
    appId: '1:815968784329:web:cdcf6b14bb517a5b77a218',
    messagingSenderId: '815968784329',
    projectId: 'chatapp-16248',
    authDomain: 'chatapp-16248.firebaseapp.com',
    storageBucket: 'chatapp-16248.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9AWo1Hn99nJ9LA10XB1gpFkJJAx_Y2RY',
    appId: '1:815968784329:android:1f1576189b8bf4dc77a218',
    messagingSenderId: '815968784329',
    projectId: 'chatapp-16248',
    storageBucket: 'chatapp-16248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-BgrlR-hmf5kZ1scPuO4UPw_gHy0ALQI',
    appId: '1:815968784329:ios:8d8ae9444290cee877a218',
    messagingSenderId: '815968784329',
    projectId: 'chatapp-16248',
    storageBucket: 'chatapp-16248.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-BgrlR-hmf5kZ1scPuO4UPw_gHy0ALQI',
    appId: '1:815968784329:ios:8d8ae9444290cee877a218',
    messagingSenderId: '815968784329',
    projectId: 'chatapp-16248',
    storageBucket: 'chatapp-16248.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrXbZ8h2JtT1jlctMmhYotsBsyg4-IJE',
    appId: '1:815968784329:web:beb373434639fc6977a218',
    messagingSenderId: '815968784329',
    projectId: 'chatapp-16248',
    authDomain: 'chatapp-16248.firebaseapp.com',
    storageBucket: 'chatapp-16248.appspot.com',
  );
}
